create table if not exists public.content_releases (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text not null,
  category_count integer not null default 0 check (category_count >= 0),
  image_count integer not null default 0 check (image_count >= 0),
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.content_releases enable row level security;

create policy "Published content releases are publicly readable"
on public.content_releases
for select
using (published_at <= now());

create index if not exists content_releases_published_at_idx
on public.content_releases (published_at desc);
